---

- name: Enable the shared IP address variable
  command: "{{ item }}"
  with_items:
    - "echo 'net.ipv4.ip_nonlocal_bind=1' > /etc/sysctl.conf"
    - "sysctl -p /etc/sysctl.conf"

- name: Install keepalived (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  environment: "{{ proxy_env }}"
  yum:
    name: keepalived
    state: latest

- name: Install keepalived (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  environment: "{{ proxy_env }}"
  apt:
    name: keepalived
    state: latest
    update_cache: yes

- name: Create keepalived  config directory
  file: path="/etc/keepalived" state=directory

- name: Copy Keepalived config file
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"

- name: Enable and restart keepalived engine
  systemd:
    name: keepalived
    daemon_reload: yes
    state: restarted
    enabled: yes
